# Generated by Django 5.2.14 on 2026-05-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_action_items_generated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_summaries_generated',
            field=models.IntegerField(default=0),
        ),
    ]
