# Generated by Django 5.2.14 on 2026-05-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_api', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
